# Dockerfile

# Use Node.js to build the app
FROM node:20 AS build

WORKDIR /client

# Clone the repository
RUN git clone https://loic-hpp:glpat-v9Qt8vbw2zoY-stynsRH@gitlab.com/polytechnique-montr-al/inf3995/20243/equipe-107/geppetto.git
RUN cd geppetto/client

# Install dependencies
RUN npm ci

# Expose the port
EXPOSE 4200

# Start the app
CMD ["npm", "start"]
